[[ -s ~/bin/dotfiles/bash/secret ]] && source ~/bin/dotfiles/bash/secret
. ~/bin/dotfiles/bash/env
. ~/bin/dotfiles/bash/config
. ~/bin/dotfiles/bash/aliases
if [[ $(uname) == 'Linux' ]]; then
   . /etc/bash_completion
   . /usr/lib/git-core/git-sh-prompt
else
   . $BREW_HOME/etc/profile.d/bash_completion.sh
fi

for f in ~/bin/dotfiles/bash/completions/*; do
   . $f
done


