set nocompatible               " be iMproved
filetype off                   " required!

set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#begin()

" let Vundle manage Vundle
" required!
Plugin 'gmarik/Vundle.vim'

" Plugins

Plugin 'ervandew/supertab'
Plugin 'Valloric/YouCompleteMe'
Plugin 'SirVer/ultisnips'
Plugin 'git@github.com:andersjanmyr/ultisnip-snippets.git'
Plugin 'airblade/vim-gitgutter'
Plugin 'altercation/vim-colors-solarized'
Plugin 'andersjanmyr/vim-scratch'
Plugin 'baeuml/summerfruit256.vim'
Plugin 'cespare/vim-toml'
Plugin 'digitaltoad/vim-jade'
Plugin 'dsolstad/vim-wombat256i'
Plugin 'malclocke/vim-buster'
Plugin 'edsono/vim-matchit'
Plugin 'evanmiller/nginx-vim-syntax'
Plugin 'fatih/vim-go'
Plugin 'freitass/todo.txt-vim.git'
Plugin 'godlygeek/tabular'
Plugin 'groenewege/vim-less'
Plugin 'guns/vim-clojure-static'
Plugin 'elzr/vim-json'
Plugin 'kana/vim-textobj-user'
Plugin 'kchmck/vim-coffee-script'
Plugin 'kien/ctrlp.vim'
Plugin 'kien/rainbow_parentheses.vim'
Plugin 'matthias-guenther/hammer.vim'
Plugin 'mattn/gist-vim'
Plugin 'mattn/webapi-vim'
Plugin 'mattn/emmet-vim'
Plugin 'mxw/vim-jsx.git'
Plugin 'nelstrom/vim-textobj-rubyblock'
Plugin 'nelstrom/vim-visual-star-search'
Plugin 'pangloss/vim-javascript'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'
Plugin 'thoughtbot/vim-rspec'
Plugin 'tomtom/tcomment_vim'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-leiningen'
Plugin 'tpope/vim-projectionist'
Plugin 'tpope/vim-dispatch'
Plugin 'tpope/vim-fireplace'
Plugin 'tpope/vim-classpath'
Plugin 'tpope/vim-git'
Plugin 'tpope/vim-haml'
Plugin 'tpope/vim-markdown'
Plugin 'tpope/vim-ragtag'
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-rake'
Plugin 'tpope/vim-repeat.git'
Plugin 'tpope/vim-sensible'
Plugin 'tpope/vim-abolish'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-unimpaired'
Plugin 'guns/vim-sexp'
Plugin 'tpope/vim-sexp-mappings-for-regular-people'
Plugin 'vim-ruby/vim-ruby'
Plugin 'wavded/vim-stylus'
Plugin 'endel/vim-github-colorscheme'
Plugin 'gregspurrier/vim-midje'
Plugin 'StanAngeloff/php.vim'

call vundle#end()            " required
filetype plugin indent on

set t_Co=256
let g:solarized_termcolors=256
colorscheme solarized
if has("mac")
  silent! set nomacatsui
else
  set lazyredraw
end

" , is a more accessible leader
let mapleader = ","
nnoremap \ ,
set timeoutlen=500 " the delay before the leader kicks in.

set background=dark " we plan to use a light background
set backup " make backup files
set backupdir=$HOME/.vim/backup " where to put backup files
set directory=$HOME/.vim/backup " where to put backup files
set cmdheight=2 " Make room for larger commands without Enter
set clipboard+=unnamed " share windows clipboard
set cursorline
set enc=utf-8
set expandtab " no real tabs please!
set formatoptions=qrn1
set gdefault
set grepprg=ack
set hidden " you can change buffers without saving
set hlsearch "Highlight search"
set history=400 "Larger history
set ignorecase " case insensitive by default
set lbr
set list
" set listchars=tab:▸\ ,eol:¬
set nocompatible " explicitly get out of vi-compatible mode
set noexrc " don't use local version of .(g)vimrc, .exrc
set number " enable line numbers
set colorcolumn=85
set undofile
set undodir=$HOME/.vim/undo " where to put backup files
set shell=bash
set splitbelow
set splitright
set shortmess=atI " Use short messages to prevent press enter...
set smartcase " Smart searching for capitalized words
set spell
set statusline=%<%f\ %h%m%r%{fugitive#statusline()}%=%-14.(%l,%c%V%)\ %P
set textwidth=79
set tabstop=2
set softtabstop=2
set shiftwidth=2
set visualbell
set wildmode=list:longest,full "Magic completion menu"
set wrap


" Autocommands
augroup RUBY
  autocmd!
  " Enable rspec support
  autocmd BufNewFile,BufRead */spec/**/*.rb,*_spec.rb compiler rspec
  autocmd BufNewFile,BufRead */test/**/*.rb,*_test.rb compiler rubyunit
  autocmd FileType ruby,eruby set omnifunc=rubycomplete#Complete
  autocmd FileType ruby,eruby let g:rubycomplete_buffer_loading = 1
  autocmd FileType ruby,eruby let g:rubycomplete_rails = 1
  autocmd FileType ruby,eruby let g:rubycomplete_classes_in_global = 1
augroup END

augroup MARKDOWN
  autocmd!
  autocmd FileType markdown,man map <Leader>p :w<CR>:!markdown < % > %.html && open %.html<CR><CR>
  autocmd FileType markdown,man map <Leader>h1 :.g/.\+/copy. <Bar> s/./=/g <CR>
  autocmd FileType markdown,man map <Leader>h2 :.g/.\+/copy. <Bar> s/./-/g <CR>
augroup END

" Jump to last position unless it is invalid or event handler
autocmd BufReadPost *
  \ if line("'\"") > 1 && line("'\"") <= line("$") |
  \   exe "normal! g`\"" |
  \ endif

inoremap <M-o>       <Esc>o
inoremap <C-j>       <Down>
let g:ragtag_global_maps = 1

let g:gist_clip_command = 'pbcopy'
let g:gist_detect_filetype = 1
let g:gist_open_browser_after_post = 1

let NERDSpaceDelims = 1
let NERDTreeIgnore=['\.rbc$', '\~$']

" Save with sudo
cmap w!! %!sudo tee > /dev/null %

" Remappings
" Visual tabbing should stay in visual
vmap > >gv
vmap < <gv


" allow a more natural style of line editing in :ex mode
cnoremap <C-A> <Home>
cnoremap <C-E> <End>
cnoremap <C-L> <Right>
cnoremap <C-H> <Left>
cnoremap <C-B> <S-Left>
cnoremap <C-W> <S-Right>
cnoremap <C-p> <Up>
cnoremap <C-n> <Down>

" Enable saving with :W too
command! W :w

nnoremap / /\v
vnoremap / /\v

nnoremap j gj
nnoremap k gk

inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>
inoremap § <ESC>
nnoremap § <ESC>
vnoremap § <ESC>
inoremap jj <ESC>
inoremap :w <ESC>:w

" Window movement
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

nnoremap <leader><space> :noh<cr>
nnoremap <leader>a <C-^>
nnoremap <leader>h :Hammer<CR>
nnoremap <leader>v V`]
nnoremap <leader>ev <C-w><C-v><C-l>:e $MYVIMRC<cr>
map <Leader>n :NERDTreeToggle<CR>
map <Leader>nf :NERDTreeFind<CR>
map <Leader>nF :NERDTreeFocus<CR>

" Normal mode: <Leader>e
map <Leader>e :e <C-R>=expand("%:p:h") . "/" <CR>
cnoremap %% <C-R>=expand('%:h').'/'<cr>
nnoremap <leader>p :bufdo set ei-=Syntax \| do Syntax \| hardcopy! >%:t.ps


nnoremap <leader>gs :Gstatus<cr>
nnoremap <leader>gd :Gdiff<cr>
nnoremap <leader>gc :Gcommit<cr>
nnoremap <leader>gb :Gblame<cr>
nnoremap <leader>gl :Glog<cr>
nnoremap <leader>gp :Git push<cr>
nnoremap <leader>gg :Ggrep <C-R><C-W>
nnoremap <leader>q :sp ~/bin/dotfiles/vim/vim-quick.md<CR>

" Replace repeat last substitution to include flags
nnoremap & :&&<CR>
xnoremap & :&&<CR>

" TComment Options
map <Leader>c :TComment<CR>

"Fugitive
autocmd BufReadPost fugitive://* set bufhidden=delete
autocmd User fugitive
   \ if fugitive#buffer().type() =~# '^\%(tree\|blob\)$' |
   \  nnoremap <buffer> .. :edit %:h<CR> |
   \ endif

"Ragtag
let g:ragtag_global_maps = 1

"Gist
let g:gist_clip_command = 'pbcopy'
let g:gist_detect_filetype = 1
let g:gist_open_browser_after_post = 1



xnoremap * :<C-u>call <SID>VSetSearch()<CR>/<C-R>=@/<CR><CR>
xnoremap # :<C-u>call <SID>VSetSearch()<CR>?<C-R>=@/<CR><CR>

function! <SID>StripTrailingWhitespaces()
    " Preparation: save last search, and cursor position.
    let _s=@/
    let l = line(".")
    let c = col(".")
    " Do the business:
    %s/\s\+$//e
    " Clean up: restore previous search history, and cursor position
    let @/=_s
    call cursor(l, c)
endfunction
nnoremap <Leader>w :call <SID>StripTrailingWhitespaces()<CR>

function! s:VSetSearch()
  let temp = @s
  norm! gv"sy
  let @/ = '\V' . substitute(escape(@s, '/\'), '\n', '\\n', 'g')
  let @s = temp
endfunction

" Set tabstop, softtabstop and shiftwidth to the same value
command! -nargs=* Stab call Stab()
function! Stab()
  let l:tabstop = 1 * input('set tabstop = softtabstop = shiftwidth = ')
  if l:tabstop > 0
    let &l:sts = l:tabstop
    let &l:ts = l:tabstop
    let &l:sw = l:tabstop
  endif
  call SummarizeTabs()
endfunction

function! SummarizeTabs()
  try
    echohl ModeMsg
    echon 'tabstop='.&l:ts
    echon ' shiftwidth='.&l:sw
    echon ' softtabstop='.&l:sts
    if &l:et
      echon ' expandtab'
    else
      echon ' noexpandtab'
    endif
  finally
    echohl None
  endtry
endfunction



"CtrlP
" CtrlP Options
let g:ctrlp_working_path_mode = 'r'
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*~,.git/*,tags,gems.tags,libs.tags,php.tags*/.sass-cache/*,*/target/*
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/](\.git|\.hg|\.svn|node_modules|gems)$',
  \ 'file': '\v\.(tags|so)$',
  \ 'link': 'some_bad_symbolic_links',
  \ }
let g:ctrlp_map = '<D-t>'
let g:ctrlp_prompt_mappings = {
      \ 'ToggleRegex()':        ['<C-t>'],
      \ 'PrtClearCache()':      ['<C-r>'],
      \ }
let g:ctrlp_switch_buffer = 1
nnoremap <C-p> :CtrlP<cr>
nnoremap <silent> <Leader>b :CtrlP<cr>
let g:ctrlp_root_markers = ['.ctrlp']

"Surround
xmap s <Plug>VSurround

autocmd FileType javascript setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType sass setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType php setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType coffee setlocal ts=4 sts=4 sw=4 expandtab
autocmd FileType less setlocal ts=4 sts=4 sw=4 expandtab


au FocusLost * :silent! wall                 " Save on FocusLost
au FocusLost * call feedkeys("\<C-\>\<C-n>") " Return to normal mode on FocustLost

set tags+=gems.tags
set tags+=libs.tags
set tags+=php.tags

set runtimepath+=~/.vim/bundle/ultisnip-snippets
let g:UltiSnipsSnippetsDir = '~/.vim/bundle/ultisnip-snippets/UltiSnips'
let g:UltiSnipsDontReverseSearchPath = '1'
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"
let g:UltiSnipsListSnippets="<c-e>"

" make YCM compatible with UltiSnips (using supertab)
let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']
let g:SuperTabDefaultCompletionType = '<C-n>'
" let g:SuperTabDefaultCompletionType = "context"
" let g:SuperTabContextDefaultCompletionType = "<C-x><C-o>"


"Clojure
cnoremap nr Connect nrepl://localhost:
nnoremap <C-e> :Eval<CR>

let g:sexp_enable_insert_mode_mappings = 0

"Golang
autocmd FileType go setlocal nolist ts=4 sts=4 sw=4 noexpandtab
au FileType go nmap <Leader>s <Plug>(go-implements)
au FileType go nmap <Leader>i <Plug>(go-info)
au FileType go nmap <Leader>gd <Plug>(go-doc)
au FileType go nmap <Leader>gv <Plug>(go-doc-vertical)
au FileType go nmap <Leader>gb <Plug>(go-doc-browser)
au FileType go nmap <leader>r <Plug>(go-run)
au FileType go nmap <leader>t <Plug>(go-test)
au FileType go nmap <Leader>ds <Plug>(go-def-split)
let g:go_fmt_command = "goimports"
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1

let g:vim_json_syntax_conceal = 0
