#!/bin/bash
#
# git-squash in PATH
# Squash branch into current branch
# Usage: git squash $branch

set -o errexit

branch=${1?'branch is required'}

current_branch=$(git rev-parse --abbrev-ref HEAD)
temp_branch='temp-squash-branch'

cleanup() {
    git branch --quiet -D $temp_branch
}
trap cleanup EXIT

git fetch --quiet origin main:main
git checkout --quiet $branch
git checkout --quiet -b $temp_branch
git rebase --quiet main
commit_log=$(git log --reverse --pretty=format:"* %s (%h)" "main..")
git reset --quiet main
message="$branch squashed

$commit_log
"
git add :/ .
git commit --quiet -m "$message"
git checkout --quiet $current_branch
git cherry-pick --quiet $temp_branch
