#!/bin/sh

if [ $# -eq 2 ]; then
  if [ "$2" = "log" ]; then
    ssh $1 "tail -f liferay/tomcat-6.0.26/logs/catalina.out"
  else
    ssh $1 "liferay/tomcat-6.0.26/bin/catalina.sh $2"
  fi
else
  /Users/andersjanmyr/Other/liferay-portal-6.0.5/tomcat-6.0.26/bin/catalina.sh $@
fi