#!/usr/bin/env node

var express = require('express');
var fs = require('fs');

var app = express.createServer();

var dir = '.';
var port = 4000;

app.configure(function() {
  app.use(express.static(dir));
});

console.log('Serving files from ' + dir + ' on port ' + port);
app.listen(port);

app.get('/', function(req, resp) {
  fs.readdir(dir, function(err, files) {
    if (err) return resp.end(err.inspect())
    console.log(files);
      var anchors = files.map(function(f) {
        return '<a href="' + f  + '">' + f + '</a>';
      });
      resp.end(anchors.join('<br/>\n'));
  });
});
