#!/usr/bin/env node

var express = require('express');
var fs = require('fs');

var app = express();

var dir = process.env.PWD;
var port = 4000;

var argv = process.argv;
if (argv[2] && argv[2] !== '.')
    dir = argv[2];
if (argv[3])
    port = argv[3];



app.configure(function() {
  app.use(express.static(dir));
});

console.log('Serving files from ' + dir + ' on port ' + port);
app.listen(port);

app.get('/', function(req, resp) {
  fs.readdir(dir, function(err, files) {
    if (err) return resp.end(err.inspect())
    console.log(files);
      var anchors = files.map(function(f) {
        return '<a href="' + f  + '">' + f + '</a>';
      });
      resp.end(anchors.join('<br/>\n'));
  });
});
