#!/bin/bash

# Set up same defaults
set -o errexit # Exit on error
set -o nounset # It is an error to use an unset variable

# http://23053085:PASSWORD@proxy.global.sonyericsson.net:8080/

if [[ $# == 0 ]]; then
  echo "Usage: $0 <new password>"
  exit 1
fi

new_password=$1


set -i.bak "s/23053085:/$new_password" ~/.npmrc
set -i.bak "s/23053085:/$new_password" ~/bin/dotfiles/gitconfig_secret
set -i.bak "s/23053085:/$new_password" ~/bin/dotfiles/bash/secret


