#!/bin/bash

echo ". ~/bin/dotfiles/bashrc" > ~/.bashrc
echo ". ~/bin/dotfiles/bashrc" > ~/.bash_profile

function replace_file() {
  rm -f $1
  ln -s $2 $1
}


replace_file ~/.gitconfig ~/bin/dotfiles/gitconfig
replace_file ~/.gitignore ~/bin/dotfiles/gitignore

replace_file ~/.ssh/config ~/bin/dotfiles/ssh/config

replace_file ~/.gemrc ~/bin/dotfiles/gemrc
replace_file ~/.irbrc ~/bin/dotfiles/irbrc
replace_file ~/.vimrc.after ~/bin/dotfiles/vimrc.after
replace_file ~/.vimrc.before ~/bin/dotfiles/vimrc.before
replace_file ~/.gvimrc.after ~/bin/dotfiles/gvimrc.after
replace_file ~/.ackrc ~/bin/dotfiles/ackrc
replace_file ~/.inputrc ~/bin/dotfiles/inputrc
replace_file ~/.jshintrc ~/bin/dotfiles/jshintrc
replace_file ~/.jslintrc ~/bin/dotfiles/jslintrc
replace_file ~/.vim/spell ~/bin/dotfiles/vim/spell

replace_file ~/.tmux.conf ~/bin/dotfiles/tmux.conf

echo "source ~/.bashrc # to reload environment"


