#!/bin/bash

echo ". ~/bin/dotfiles/bashrc" > ~/.bashrc
echo ". ~/bin/dotfiles/bashrc" > ~/.bash_profile

function replace_file() {
  rm $1
  ln -s $2 $1
}


replace_file ~/.gitconfig ~/bin/dotfiles/gitconfig
replace_file ~/.gitignore ~/bin/dotfiles/gitignore
replace_file ~/.gemrc ~/bin/dotfiles/gemrc
replace_file ~/.ssh/config ~/bin/dotfiles/ssh/config


echo "source ~/.bashrc # to reload environment"


